const metas=[{valor:100000,premio:"Moto elétrica"},{valor:200000,premio:"Smartphone premium"},{valor:500000,premio:"Viagem internacional para casal"},{valor:1500000,premio:"Carro elétrico básico"},{valor:4000000,premio:"Carro elétrico de luxo"}];
function seed(){if(!localStorage.getItem("clientesDellapiani")){localStorage.setItem("clientesDellapiani",JSON.stringify([{nome:"Cliente Exemplo",documento:"00000000000",pontos:12500,compras:180000},{nome:"Arquitetura Prime",documento:"11111111111",pontos:36500,compras:510000},{nome:"Construtora Recife",documento:"22222222222",pontos:82000,compras:1520000}]))}if(!localStorage.getItem("promosDellapiani")){localStorage.setItem("promosDellapiani",JSON.stringify([{titulo:"Black Premium",desc:"Compre produtos participantes e avance em metas para conquistar grandes benefícios.",pontos:10000},{titulo:"Semana do Arquiteto",desc:"Condições especiais para escritórios parceiros e profissionais especificadores.",pontos:3000},{titulo:"Cashback Revestimentos",desc:"Pontos extras em linhas selecionadas de acabamento, porcelanato e revestimentos.",pontos:5000}]))}}
function limparDoc(v){return(v||"").replace(/\D/g,"")}function dinheiro(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}function pontos(v){return Number(v||0).toLocaleString("pt-BR")+" pts"}
function carregarPromos(){const promos=JSON.parse(localStorage.getItem("promosDellapiani")||"[]");document.getElementById("statPromos").innerText=promos.length;document.getElementById("promocoesGrid").innerHTML=promos.map(p=>`<article class="promo-card"><span class="tag">${pontos(p.pontos)}</span><h3>${p.titulo}</h3><p class="muted">${p.desc}</p><a class="btn btn-dark" href="#pontos">Consultar elegibilidade</a></article>`).join("")}
function carregarRanking(){const clientes=JSON.parse(localStorage.getItem("clientesDellapiani")||"[]").sort((a,b)=>b.pontos-a.pontos);document.getElementById("rankingBody").innerHTML=clientes.map((c,i)=>`<tr><td>#${i+1}</td><td><b>${c.nome}</b></td><td>${pontos(c.pontos)}</td><td>${dinheiro(c.compras)}</td><td>${c.compras>=500000?"Premium":"Ativo"}</td></tr>`).join("")}
function salvarCliente(){const clientes=JSON.parse(localStorage.getItem("clientesDellapiani")||"[]");const novo={nome:document.getElementById("nome").value.trim(),documento:limparDoc(document.getElementById("documento").value),pontos:Number(document.getElementById("pontos").value||0),compras:Number(document.getElementById("compras").value||0)};if(!novo.nome||!novo.documento){alert("Preencha nome e CPF/CNPJ.");return}const idx=clientes.findIndex(c=>c.documento===novo.documento);if(idx>=0)clientes[idx]=novo;else clientes.push(novo);localStorage.setItem("clientesDellapiani",JSON.stringify(clientes));carregarRanking();alert("Cliente salvo com sucesso!")}
function salvarPromo(){const promos=JSON.parse(localStorage.getItem("promosDellapiani")||"[]");const nova={titulo:document.getElementById("tituloPromo").value.trim(),desc:document.getElementById("descPromo").value.trim(),pontos:Number(document.getElementById("pontosPromo").value||0)};if(!nova.titulo){alert("Informe o título da promoção.");return}promos.push(nova);localStorage.setItem("promosDellapiani",JSON.stringify(promos));carregarPromos();alert("Promoção salva com sucesso!")}
function buscarCliente(){const doc=limparDoc(document.getElementById("docCliente").value);const clientes=JSON.parse(localStorage.getItem("clientesDellapiani")||"[]");const cliente=clientes.find(c=>c.documento===doc);const box=document.getElementById("clienteResultado");if(!cliente){box.innerHTML=`<p><b>Cadastro não encontrado.</b><br><span class="muted">Fale com um consultor para atualizar seu cadastro e pontos.</span></p>`;return}const proxima=metas.find(m=>cliente.compras<m.valor)||metas[metas.length-1];const faltam=Math.max(0,proxima.valor-cliente.compras);const perc=Math.min(100,(cliente.compras/proxima.valor)*100);document.getElementById("dashPontos").innerText=pontos(cliente.pontos);document.getElementById("dashCompras").innerText=dinheiro(cliente.compras);document.getElementById("dashMeta").innerText=dinheiro(proxima.valor);document.getElementById("dashBar").style.width=perc+"%";document.getElementById("dashFalta").innerText=`Faltam ${dinheiro(faltam)} para ${proxima.premio}.`;document.getElementById("heroPoints").innerText=pontos(cliente.pontos);box.innerHTML=`<h3>Olá, ${cliente.nome}</h3><p><b>Saldo:</b> ${pontos(cliente.pontos)}</p><p><b>Compras acumuladas:</b> ${dinheiro(cliente.compras)}</p><p><b>Próxima conquista:</b> ${proxima.premio}</p><a class="btn btn-gold" href="https://wa.me/5581999999999" target="_blank">Solicitar atendimento</a>`}
seed();carregarPromos();carregarRanking();
